[project]
name = "purwahitung"
version = "0.1.0"
description = ""
authors = [
    {name = "Herman Sugi Harto",email = "hermansh.id@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.11,<4.0.0"
dependencies = [
    "fastmcp (>=4.0.11,<5.0.0)",
    "langchain (>=1.4.3,<2.0.0)",
    "langchain[mcp] (>=1.4.3,<2.0.0)",
    "langchain-openai (>=1.6.7,<2.0.0)",
    "langchain-openrouter (>=0.2.9,<0.3.0)",
    "python-dotenv (>=1.2.4,<2.0.0)"
]

[tool.poetry]
packages = [{include = "purwahitung", from = "src"}]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
